/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // The docs/ tree is assembled at build time by scripts/clone-docs.sh +
  // scripts/prepare-docs.sh, so the sidebar is generated from that tree.
  // Ordering is controlled by sidebar_position front matter and _category_.json
  // files injected by prepare-docs.sh.
  defaultSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
